name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Kódu
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Nastavení GCC a Dalších Nástrojů
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-10 g++-10 make valgrind doxygen graphviz
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
        gcc --version
        g++ --version

    - name: Vytvoření Adresářů pro Logy a Dokumentaci
      run: |
        mkdir -p logs
        mkdir -p docs/html

    - name: Zobrazení Obsahu Kořenového Adresáře
      run: |
        echo "Obsah kořenového adresáře:"
        ls -al

    - name: Zobrazení Obsahu framework/
      run: |
        echo "Obsah framework/:"
        ls -al framework/

    - name: Sestavení Frameworku (Debug Režim)
      run: |
        make -C framework BUILD=debug

    - name: Sestavení Frameworku (Release Režim)
      run: |
        make -C framework BUILD=release

    - name: Sestavení Sdílené Knihovny (Verbose)
      run: |
        make -C framework shared

    - name: Instalace Knihovny a Hlaviček
      run: |
        make -C framework install DESTDIR=${{ github.workspace }}/install

    - name: Spuštění Testů
      run: |
        make -C framework test

    - name: Kontrola Paměťových Úniků pomocí Valgrind
      run: |
        make -C framework memcheck

    - name: Generování Dokumentace pomocí Doxygen
      run: |
        make -C framework docs

    - name: Publikace Dokumentace jako GitHub Pages (Volitelně)
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
        publish_branch: gh-pages
        user_name: 'github-actions'
        user_email: 'github-actions@github.com'

    - name: Cache Make Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache
          framework/obj
          framework/lib
        key: ${{ runner.os }}-make-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-make-
