name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Kódu
      uses: actions/checkout@v3

    - name: Nastavení GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-10 g++-10
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
        gcc --version
        g++ --version

    - name: Instalace Závislostí
      run: |
        sudo apt-get update
        sudo apt-get install -y make valgrind doxygen graphviz

    - name: Vytvoření Adresářů pro Logy a Dokumentaci
      run: |
        mkdir -p logs
        mkdir -p docs/html

    - name: Zobrazení Obsahu Kořenového Adresáře
      run: |
        echo "Obsah kořenového adresáře:"
        ls -al

    - name: Sestavení Frameworku (Debug Režim)
      run: |
        make BUILD=debug

    - name: Sestavení Frameworku (Release Režim)
      run: |
        make BUILD=release

    - name: Sestavení Sdílené Knihovny
      run: |
        make shared

    - name: Instalace Knihovny a Hlaviček
      run: |
        make install DESTDIR=${{ github.workspace }}/install

    - name: Sestavení Projektu
      run: |
        make build

    - name: Spuštění Testů
      run: |
        make test

    - name: Kontrola Paměťových Úniků pomocí Valgrind
      run: |
        make memcheck

    - name: Generování Dokumentace pomocí Doxygenu
      run: |
        make docs

    - name: Publikace Dokumentace jako GitHub Pages (Volitelně)
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
        publish_branch: gh-pages
        user_name: 'github-actions'
        user_email: 'github-actions@github.com'
