name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kódu
      uses: actions/checkout@v2

    - name: Instalace Závislostí
      run: sudo apt-get update && sudo apt-get install -y gcc make valgrind

    - name: Sestavení Frameworku
      run: |
        cd framework
        make
        cd ..

    - name: Sestavení Projektu
      run: make

    - name: Spuštění Testů
      run: make test

    - name: Kontrola Paměťových Úniků
      run: valgrind --leak-check=full ./build/main
